### ISSUE TITLE
Usability question

### ISSUE THREAD

**Issue by alichtman** [wren/jrnl.vim#1]
To use this, do you set the default syntax for `.txt` files to `jrnl`?

**Comment by wren** [comment]
The latest versions of jrnl (v2.7+) use `.jrnl` as the file extension when using an editor, so setting the default syntax for `.jrnl` will enable this.

If you use a template for a specific journal, jrnl will copy the file extension of your template, in which case you can decide what extension you prefer to use.

Does that answer your question?

**Comment by wren** [comment]
@alichtman Did that answer your question?

**Comment by alichtman** [comment]
Thanks! Updated jrnl and it works with:

```vim
autocmd BufRead,BufNewFile *.jrnl set filetype=jrnl
```
